#!/bin/bash
# first grep: prevent filename contamination (filter out obsolete name like 1024_iii.c)

case $# in
  0) pattern='// Tag: ' ;;
  *) pattern=$*         ;;
esac

head $(find -name '*.cpp') -n1 | grep -B1 '// Tag: ' | grep -B1 "$pattern"
