#!/bin/bash

case $# in
  1) filename="$1"  ;;
  *) echo -e "Usage: xx FILE, alias for:
  g++ FILE -ggdb && ./a.out < in && xclip FILE"; exit 1 ;;
esac

g++ "$filename" -ggdb && ./a.out < "in" && xclip -selection c "$filename"
