#!/bin/bash

case $# in
  1) filename="$1"  ;;
  *) echo -e "Usage: xxd FILE, alias for:
  g++ FILE -DDEBUG -ggdb && ./a.out < in && xclip FILE"; exit 1 ;;
esac

g++ "$filename" -DDEBUG -ggdb && ./a.out < "in" && xclip "$filename"
